name: CMake

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        include:
        - cc: gcc
          cxx: g++
          os: ubuntu-22.04
        - cc: gcc
          cxx: g++
          os: ubuntu-24.04
        - cc: clang
          cxx: clang++
          os: ubuntu-24.04
      fail-fast: false

    runs-on: ${{matrix.os}}

    env:
      CC: ${{matrix.cc}}
      CXX: ${{matrix.cxx}}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -yq libkmod-dev libpci-dev libtool-bin

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j

    - name: Package
      working-directory: ${{github.workspace}}/build
      run: cpack

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: libpda-${{matrix.os}}-${{matrix.cc}}
        path: ${{github.workspace}}/build/libpda*.deb
