name: pda-kernel

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -yq build-essential debhelper dh-dkms dkms devscripts linux-headers-`uname -r`

    - name: Build
      run: make deb

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: pda-kernel-dkms.deb
        path: pda-kernel-dkms*.deb
