name: pda-kernel

on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-22.04
        - os: ubuntu-24.04
      fail-fast: false

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install -yq debhelper dkms devscripts linux-headers-`uname -r`

    - name: Install dependencies
      if: ${{ matrix.os == 'ubuntu-24.04' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install -yq build-essential debhelper dh-dkms dkms devscripts linux-headers-`uname -r`

    - name: Build module
      run: make -C patches/linux_uio build

    - name: Build .deb
      run: make deb

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: pda-kernel-dkms-${{matrix.os}}
        path: pda-kernel-dkms*.deb
